## Load ipython-sql

In [1]:
%load_ext sql

## Connect to postgresql database

In [3]:
%sql postgresql+psycopg2://alexandergelernter:password123@localhost:5432/intro_to_sql_for_analytics

## Run Queries

In [5]:
%%sql

SELECT *
FROM billboard_top_100_year_end
WHERE "year" = 1988 AND "year_rank" = 2;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
1 rows affected.

[(3290, 1988, 2, 'INXS', 'INXS', 'Need You Tonight', 3291.0)]

In [8]:
%%sql

SELECT *
FROM coaches

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
91 rows affected.

[(0, 'AGHAKOUCHEKI Abbas', 'Islamic Republic of Iran', 'IRI', 'Wheelchair Basketball', 'WBK', 'Men'),
 (1, 'AKIN Ahmet', 'Turkey', 'TUR', 'Wheelchair Basketball', 'WBK', 'Men'),
 (2, 'AKPWEH Toussaint', 'France', 'FRA', 'Football 5-a-side', 'FB5', 'Men'),
 (3, 'ARIMA Masato', 'Japan', 'JPN', 'Wheelchair Basketball', 'WBK', None),
 (4, 'BAN Nicole', 'Canada', 'CAN', 'Sitting Volleyball', 'VBS', 'Women'),
 (5, 'BARGUEIRAS MARTINEZ Jesus David', 'Spain', 'ESP', 'Football 5-a-side', 'FB5', 'Men'),
 (6, 'BHANIA Haj', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', None),
 (7, 'BOUTIBA Saad', 'Algeria', 'ALG', 'Goalball', 'GBL', 'Men'),
 (8, 'BRAHIMI Mustapha', 'Algeria', 'ALG', 'Wheelchair Basketball', 'WBK', 'Men'),
 (9, 'CARRION RUIZ Abraham', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', 'Women'),
 (10, 'CHEN Qi', "People's Republic of China", 'CHN', 'Wheelchair Basketball', 'WBK', 'Women'),
 (11, 'CHOUDHRY Gaz', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', 'Men'),
 (12, 'CORR Peter', 'Australia', 'AUS', 'Goalball', 'GBL', 'Women'),
 (13, 'COTE Patrick', 'Canada', 'CAN', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (14, 'CUSIN Olivier', 'France', 'FRA', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (15, 'CZECHOWSKI Jake', 'United States of America', 'USA', 'Goalball', 'GBL', 'Women'),
 (16, 'de RICK Johan', 'Belgium', 'BEL', 'Goalball', 'GBL', 'Men'),
 (17, 'DEMONTE Martin', 'Argentina', 'ARG', 'Football 5-a-side', 'FB5', 'Men'),
 (18, 'DO NASCIMENTO CARDOSO Ana Lucia', 'Colombia', 'COL', 'Wheelchair Basketball', 'WBK', 'Men'),
 (19, 'DUBBERLEY Brad', 'Australia', 'AUS', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (20, 'DUBROVIN Anton', 'Ukraine', 'UKR', 'Goalball', 'GBL', 'Men'),
 (21, 'DUBROVIN Fedir', 'Ukraine', 'UKR', 'Goalball', 'GBL', 'Men'),
 (22, 'DUCHARME Marc Antoine', 'Canada', 'CAN', 'Wheelchair Basketball', 'WBK', 'Women'),
 (23, 'EDRIS Gharib', 'Egypt', 'EGY', 'Sitting Volleyball', 'VBS', None),
 (24, 'EL MOUNTAQI Driss', 'Morocco', 'MAR', 'Football 5-a-side', 'FB5', 'Men'),
 (25, 'ELAIUTY Mosaad', 'Egypt', 'EGY', 'Sitting Volleyball', 'VBS', 'Men'),
 (26, 'ELIA GIMENO Raul', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', None),
 (27, 'ELTAYEB Hani', 'Egypt', 'EGY', 'Goalball', 'GBL', 'Women'),
 (28, 'FAREBROTHER Trent', 'Canada', 'CAN', 'Goalball', 'GBL', 'Women'),
 (29, 'FERIANI Matteo', 'Canada', 'CAN', 'Wheelchair Basketball', 'WBK', 'Men'),
 (30, 'FISHER Simon', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', 'Women'),
 (31, 'FREITAS DO NASCIMENTO Dailton', 'Brazil', 'BRA', 'Goalball', 'GBL', 'Women'),
 (32, 'FRIDAY Craig', 'Australia', 'AUS', 'Wheelchair Basketball', 'WBK', 'Men'),
 (33, 'FRIDAY Craig', 'Australia', 'AUS', 'Wheelchair Basketball', 'WBK', 'Women'),
 (34, 'FURNESS Shane', 'Australia', 'AUS', 'Wheelchair Basketball', 'WBK', None),
 (35, 'GECEVICIUS Valdas', 'Lithuania', 'LTU', 'Goalball', 'GBL', 'Men'),
 (36, 'GUEDES DANTAS Jose', 'Brazil', 'BRA', 'Sitting Volleyball', 'VBS', 'Women'),
 (37, 'GUENTHER Johannes', 'Germany', 'GER', 'Goalball', 'GBL', 'Men'),
 (38, 'GUMBERT James', 'United States of America', 'USA', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (39, 'HAMITER William', 'United States of America', 'USA', 'Sitting Volleyball', 'VBS', 'Women'),
 (40, 'HRUSTEMOVIC Mirza', 'Bosnia and Herzegovina', 'BIH', 'Sitting Volleyball', 'VBS', 'Men'),
 (41, 'ICHIKAWA Kyoichi', 'Japan', 'JPN', 'Goalball', 'GBL', 'Women'),
 (42, 'IWASA Yoshiaki', 'Japan', 'JPN', 'Wheelchair Basketball', 'WBK', 'Women'),
 (43, 'JOHNSON Lawrence', 'United States of America', 'USA', 'Wheelchair Basketball', 'WBK', 'Women'),
 (44, 'KARASU Gultekin', 'Turkey', 'TUR', 'Goalball', 'GBL', 'Women'),
 (45, 'KIM Hyun Woo', 'Republic of Korea', 'KOR', 'Wheelchair Basketball', 'WBK', None),
 (46, 'KO Kwangyub', 'Republic of Korea', 'KOR', 'Wheelchair Basketball', 'WBK', None),
 (47, 'KO Kwangyub', 'Republic of Korea', 'KOR', 'Wheelchair Basketball', 'WBK', 'Men'),
 (48, 'KONGDANPRAI Kongkiat', 'Thailand', 'THA', 'Football 5-a-side', 'FB5', 'Men'),
 (49, 'KRYVENKO Kseniia', 'Ukraine', 'UKR', 'Sitting Volleyball', 'VBS', None),
 (50, 'KUBO Yoshihiro', 'Japan', 'JPN', 'Sitting Volleyball', 'VBS', 'Men'),
 (51, 'KUDO Rikiya', 'Japan', 'JPN', 'Goalball', 'GBL', 'Men'),
 (52, 'KYOYA Kazuyuki', 'Japan', 'JPN', 'Wheelchair Basketball', 'WBK', 'Men'),
 (53, 'LAWRENCE Matt', 'Great Britain', 'GBR', 'Goalball', 'GBL', None),
 (54, 'LAWRENCE Matt', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', None),
 (55, 'LYKINS Ron', 'United States of America', 'USA', 'Wheelchair Basketball', 'WBK', 'Men'),
 (56, 'MANO Yoshihisa', 'Japan', 'JPN', 'Sitting Volleyball', 'VBS', 'Women'),
 (57, 'MEDIATO Celio', 'Brazil', 'BRA', 'Sitting Volleyball', 'VBS', 'Men'),
 (58, 'MERTEN Michael', 'Germany', 'GER', 'Sitting Volleyball', 'VBS', 'Men'),
 (59, 'MIKAMI Yukako', 'Japan', 'JPN', 'Goalball', 'GBL', None),
 (60, 'MITCHELL Greg', 'New Zealand', 'NZL', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (61, 'NABIEV Ilkam', 'RPC', 'RPC', 'Goalball', 'GBL', 'Women'),
 (62, 'NOHL Dennis', 'Germany', 'GER', 'Wheelchair Basketball', 'WBK', 'Women'),
 (63, 'NSENGIYUMVA Jean Marie', 'Rwanda', 'RWA', 'Sitting Volleyball', 'VBS', 'Women'),
 (64, 'ORR Kevin', 'Japan', 'JPN', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (65, 'OVSYANNIKOV Aleksandr', 'RPC', 'RPC', 'Sitting Volleyball', 'VBS', 'Men'),
 (66, 'OVSYANNIKOV Aleksandr', 'RPC', 'RPC', 'Sitting Volleyball', 'VBS', 'Women'),
 (67, 'PASCIARI Guido', 'Italy', 'ITA', 'Sitting Volleyball', 'VBS', None),
 (68, 'PISKOVA Yuliia', 'Ukraine', 'UKR', 'Sitting Volleyball', 'VBS', None),
 (69, 'RADMORE Colin', 'Great Britain', 'GBR', 'Goalball', 'GBL', None),
 (70, 'RADMORE Colin', 'Great Britain', 'GBR', 'Wheelchair Basketball', 'WBK', None),
 (71, 'REGIER Jason', 'Denmark', 'DEN', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (72, 'RENCBER Salih', 'Turkey', 'TUR', 'Goalball', 'GBL', 'Men'),
 (73, 'REZAEI Hadi', 'Islamic Republic of Iran', 'IRI', 'Sitting Volleyball', 'VBS', 'Men'),
 (74, 'RIBEIRO Amauri', 'Italy', 'ITA', 'Sitting Volleyball', 'VBS', 'Women'),
 (75, 'RIBEIRO de VASCONCELOS Fabio', 'Brazil', 'BRA', 'Football 5-a-side', 'FB5', 'Men'),
 (76, 'SHAW Paul', 'Great Britain', 'GBR', 'Wheelchair Rugby', 'WRU', 'Mixed'),
 (77, 'SHOHAM Raz', 'Israel', 'ISR', 'Goalball', 'GBL', 'Women'),
 (78, 'TAGHICHE Ahmed', 'Algeria', 'ALG', 'Wheelchair Basketball', 'WBK', 'Women'),
 (79, 'TAKADA Satoshi', 'Japan', 'JPN', 'Football 5-a-side', 'FB5', 'Men'),
 (80, 'TANG Qun', "People's Republic of China", 'CHN', 'Goalball', 'GBL', 'Women'),
 (81, 'TAPIA LOPEZ Genoveva', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', None),
 (82, 'TOSIM Alessandro', 'Brazil', 'BRA', 'Goalball', 'GBL', 'Men'),
 (83, 'TRIGO DIEZ Oscar', 'Spain', 'ESP', 'Wheelchair Basketball', 'WBK', 'Men'),
 (84, 'van der LINDEN Gertjan', 'Netherlands', 'NED', 'Wheelchair Basketball', 'WBK', 'Women'),
 (85, 'XU Huimin', "People's Republic of China", 'CHN', 'Sitting Volleyball', 'VBS', 'Women'),
 (86, 'XU Yufei', "People's Republic of China", 'CHN', 'Football 5-a-side', 'FB5', 'Men'),
 (87, 'YE Jing', "People's Republic of China", 'CHN', 'Sitting Volleyball', 'VBS', 'Men'),
 (88, 'YIN Shiqiang', "People's Republic of China", 'CHN', 'Goalball', 'GBL', 'Men'),
 (89, 'YOUNG Keith', 'United States of America', 'USA', 'Goalball', 'GBL', 'Men'),
 (90, 'ZELTINGER Nicolai', 'Germany', 'GER', 'Wheelchair Basketball', 'WBK', 'Men')]

In [9]:
%%sql

SELECT *
FROM billboard_top_100_year_end
LIMIT 15;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
15 rows affected.

[(0, 1956, 1, 'Elvis Presley', 'Elvis Presley', 'Heartbreak Hotel', 1.0),
 (1, 1956, 2, 'Elvis Presley', 'Elvis Presley', "Don't Be Cruel", 2.0),
 (2, 1956, 3, 'Nelson Riddle', 'Nelson Riddle', 'Lisbon Antigua', 3.0),
 (3, 1956, 4, 'Platters', 'Platters', 'My Prayer', 4.0),
 (4, 1956, 5, 'Gogi Grant', 'Gogi Grant', 'The Wayward Wind', 5.0),
 (5, 1956, 6, 'Les Baxter', 'Les Baxter', 'The Poor People Of Paris', 6.0),
 (6, 1956, 7, 'Doris Day', 'Doris Day', 'Whatever Will Be Will Be (Que Sera Sera)', 7.0),
 (7, 1956, 8, 'Elvis Presley', 'Elvis Presley', 'Hound Dog', 8.0),
 (8, 1956, 9, 'Dean Martin', 'Dean Martin', 'Memories Are Made Of This', 9.0),
 (9, 1956, 10, 'Kay Starr', 'Kay Starr', 'Rock And Roll Waltz', 10.0),
 (10, 1956, 11, 'Morris Stoloff', 'Morris Stoloff', 'Moonglow And Theme From "Picnic"', 11.0),
 (11, 1956, 12, 'Platters', 'Platters', 'The Great Pretender', 12.0),
 (12, 1956, 13, 'Pat Boone', 'Pat Boone', 'I Almost Lost My Mind', 13.0),
 (13, 1956, 14, 'Elvis Presley', 'Elvis Presley', 'I Want You, I Need You, I Love You', 14.0),
 (14, 1956, 15, 'Elvis Presley', 'Elvis Presley', 'Love Me Tender', 15.0)]

In [13]:
%%sql

SELECT * FROM billboard_top_100_year_end 
WHERE artist = 'Mariah Carey' 
LIMIT 10;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
10 rows affected.

[(3502, 1990, 6, 'Mariah Carey', 'Mariah Carey', 'Vision Of Love', 3503.0),
 (3574, 1990, 76, 'Mariah Carey', 'Mariah Carey', 'Love Takes Time', 3575.0),
 (3611, 1991, 13, 'Mariah Carey', 'Mariah Carey', 'Someday', 3612.0),
 (3621, 1991, 22, 'Mariah Carey', 'Mariah Carey', 'Emotions', 3622.0),
 (3625, 1991, 26, 'Mariah Carey', 'Mariah Carey', "I Don't Wanna Cry", 3626.0),
 (3668, 1991, 69, 'Mariah Carey', 'Mariah Carey', 'Love Takes Time', 3669.0),
 (3715, 1992, 16, 'Mariah Carey', 'Mariah Carey', "I'll Be There", 3716.0),
 (3723, 1992, 23, 'Mariah Carey', 'Mariah Carey', "Can't Let Go", 3724.0),
 (3745, 1992, 42, 'Mariah Carey', 'Mariah Carey', 'Make It Happen', 3746.0),
 (3811, 1993, 8, 'Mariah Carey', 'Mariah Carey', 'Dreamlover', 3812.0)]

In [14]:
%%sql

SELECT year, song_name
FROM billboard_top_100_year_end
WHERE year_rank = 1
LIMIT 10;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
10 rows affected.

[(1956, 'Heartbreak Hotel'),
 (1957, 'All Shook Up'),
 (1958, 'Volare (Nel Blu Dipinto Di Blu)'),
 (1959, 'The Battle Of New Orleans'),
 (1960, 'Theme From "A Summer Place"'),
 (1961, "Tossin' And Turnin'"),
 (1962, 'Stranger On The Shore'),
 (1963, 'Sugar Shack'),
 (1964, 'I Want To Hold Your Hand'),
 (1965, 'Wooly Bully')]

In [15]:
%%sql

SELECT * FROM billboard_top_100_year_end
WHERE artist = 'Gogi Grant'
ORDER BY year_rank;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
1 rows affected.

[(4, 1956, 5, 'Gogi Grant', 'Gogi Grant', 'The Wayward Wind', 5.0)]

In [16]:
%%sql

SELECT year, song_name, artist FROM billboard_top_100_year_end
WHERE year_rank = 1
ORDER BY artist;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
64 rows affected.

[(2003, 'In Da Club', '50 Cent'),
 (1994, 'The Sign', 'Ace Of Base'),
 (2011, 'Rolling In The Deep', 'Adele'),
 (1978, 'Shadow Dancing', 'Andy Gibb'),
 (1969, 'Sugar, Sugar', 'Archies'),
 (1987, 'Walk Like An Egyptian', 'Bangles'),
 (1974, 'The Way We Were', 'Barbra Streisand'),
 (1964, 'I Want To Hold Your Hand', 'Beatles'),
 (1968, 'Hey Jude', 'Beatles'),
 (2007, 'Irreplaceable', 'Beyonce'),
 (1980, 'Call Me', 'Blondie'),
 (1961, "Tossin' And Turnin'", 'Bobby Lewis'),
 (1992, 'End Of The Road', 'Boyz II Men'),
 (1991, '(Everything I Do) I Do It For You', 'Bryan Adams'),
 (1975, 'Love Will Keep Us Together', 'Captain and Tennille'),
 (1999, 'Believe', 'Cher'),
 (1989, 'Look Away', 'Chicago'),
 (1995, "Gangsta's Paradise", 'Coolio'),
 (2006, 'Bad Day', 'Daniel Powter'),
 (1986, "That's What Friends Are For", 'Dionne and Friends'),
 (1958, 'Volare (Nel Blu Dipinto Di Blu)', 'Domenico Modugno'),
 (1997, 'Candle In The Wind 1997', 'Elton John'),
 (1957, 'All Shook Up', 'Elvis Presley'),
 (1956, 'Heartbreak Hotel', 'Elvis Presley'),
 (2000, 'Breathe', 'Faith Hill'),
 (2008, 'Low', 'Flo Rida'),
 (1988, 'Faith', 'George Michael'),
 (2012, 'Somebody That I Used To Know', 'Gotye'),
 (1963, 'Sugar Shack', 'Jimmy Gilmer and The Fireballs'),
 (1959, 'The Battle Of New Orleans', 'Johnny Horton'),
 (2010, 'TiK ToK', 'Ke$ha'),
 (1981, 'Bette Davis Eyes', 'Kim Carnes'),
 (2012, 'Somebody That I Used To Know', 'Kimbra'),
 (1979, 'My Sharona', 'Knack'),
 (2001, 'Hanging By A Moment', 'Lifehouse'),
 (2004, 'Yeah!', 'Lil Jon'),
 (1996, 'Macarena (Bayside Boys Mix)', 'Los Del Rio'),
 (2004, 'Yeah!', 'Ludacris'),
 (1967, 'To Sir With Love', 'Lulu'),
 (2013, 'Thrift Shop', 'Macklemore'),
 (2005, 'We Belong Together', 'Mariah Carey'),
 (1962, 'Stranger On The Shore', 'Mr. Acker Bilk'),
 (1998, 'Too Close', 'Next'),
 (2002, 'How You Remind Me', 'Nickelback'),
 (1982, 'Physical', 'Olivia Newton-John'),
 (1960, 'Theme From "A Summer Place"', 'Percy Faith'),
 (1983, 'Every Breath You Take', 'Police'),
 (1984, 'When Doves Cry', 'Prince'),
 (1972, 'The First Time Ever I Saw Your Face', 'Roberta Flack'),
 (1977, "Tonight's The Night (Gonna Be Alright)", 'Rod Stewart'),
 (2013, 'Thrift Shop', 'Ryan Lewis'),
 (1965, 'Wooly Bully', 'Sam The Sham and The Pharaohs'),
 (1966, 'The Ballad Of The Green Berets', 'Sgt. Barry Sadler'),
 (1970, 'Bridge Over Troubled Water', 'Simon and Garfunkel'),
 (2008, 'Low', 'T-Pain'),
 (2009, 'Boom Boom Pow', 'The Black Eyed Peas'),
 (1971, 'Joy To The World', 'Three Dog Night'),
 (1973, "Tie A Yellow Ribbon 'Round The Ole Oak Tree", 'Tony Orlando and Dawn'),
 (2004, 'Yeah!', 'Usher'),
 (2013, 'Thrift Shop', 'Wanz'),
 (1985, 'Careless Whisper', 'Wham!'),
 (1993, 'I Will Always Love You', 'Whitney Houston'),
 (1990, 'Hold On', 'Wilson Phillips'),
 (1976, 'Silly Love Songs', 'Wings')]

In [17]:
%%sql

SELECT * FROM billboard_top_100_year_end
WHERE year = 1979
ORDER BY year_rank DESC;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
103 rows affected.

[(2440, 1979, 100, 'Firefall', 'Firefall', 'Strange Way', 2441.0),
 (2439, 1979, 99, 'G.Q.', 'G.Q.', 'I Do Love You', 2440.0),
 (2438, 1979, 98, 'Commodores', 'Commodores', 'Sail On', 2439.0),
 (2437, 1979, 97, 'Diana Ross', 'Diana Ross', 'The Boss', 2438.0),
 (2436, 1979, 96, 'Nigel Olsson', 'Nigel Olsson', 'Dancing Shoes', 2437.0),
 (2435, 1979, 95, 'Van Halen', 'Van Halen', 'Dance The Night Away', 2436.0),
 (2434, 1979, 94, 'Bob Seger and The Silver Bullet Band', 'Bob Seger and The Silver Bullet Band', "We've Got Tonight", 2435.0),
 (2433, 1979, 93, 'Barry Manilow', 'Barry Manilow', 'Somewhere In The Night', 2434.0),
 (2432, 1979, 92, 'Robert Palmer', 'Robert Palmer', "Bad Case Of Lovin' You", 2433.0),
 (2431, 1979, 91, 'Michael Jackson', 'Michael Jackson', "Don't Stop 'Til You Get Enough", 2432.0),
 (2430, 1979, 90, 'Instant Funk', 'Instant Funk', 'I Got My Mind Made Up', 2431.0),
 (2429, 1979, 89, 'Babys', 'Babys', 'Every Time I Think Of You', 2430.0),
 (2428, 1979, 88, 'Foreigner', 'Foreigner', 'Double Vision', 2429.0),
 (2427, 1979, 87, 'Alice Cooper', 'Alice Cooper', 'How You Gonna See Me Now', 2428.0),
 (2426, 1979, 86, 'Rex Smith', 'Rex Smith', 'You Take My Breath Away', 2427.0),
 (2425, 1979, 85, 'Eddie Rabbitt', 'Eddie Rabbitt', 'Suspicions', 2426.0),
 (2424, 1979, 84, 'Ambrosia', 'Ambrosia', 'How Much I Feel', 2425.0),
 (2423, 1979, 83, 'Roger Voudouris', 'Roger Voudouris', 'Get Used To It', 2424.0),
 (2422, 1979, 82, 'Eric Clapton', 'Eric Clapton', 'Promises', 2423.0),
 (2421, 1979, 81, 'Electric Light Orchestra', 'Electric Light Orchestra', "Don't Bring Me Down", 2422.0),
 (2420, 1979, 80, 'Herb Alpert', 'Herb Alpert', 'Rise', 2421.0),
 (2419, 1979, 79, 'Al Stewart', 'Al Stewart', 'Time Passages', 2420.0),
 (2418, 1979, 78, 'Earth, Wind and Fire', 'Earth, Wind and Fire', 'September', 2419.0),
 (2417, 1979, 77, 'Linda Ronstadt', 'Linda Ronstadt', 'Ooh Baby Baby', 2418.0),
 (2416, 1979, 76, 'G.Q.', 'G.Q.', 'Disco Nights', 2417.0),
 (2415, 1979, 75, 'Gino Vannelli', 'Gino Vannelli', 'I Just Wanna Stop', 2416.0),
 (2414, 1979, 74, 'Kiss', 'Kiss', "I Was Made For Lovin' You", 2415.0),
 (2413, 1979, 73, 'Ian Matthews', 'Ian Matthews', 'Shake It', 2414.0),
 (2412, 1979, 72, 'Anne Murray', 'Anne Murray', 'I Just Fall In Love Again', 2413.0),
 (2411, 1979, 71, 'Electric Light Orchestra', 'Electric Light Orchestra', 'Shine A Little Love', 2412.0),
 (2410, 1979, 70, 'Patrick Hernandez', 'Patrick Hernandez', 'Born To Be Alive', 2411.0),
 (2409, 1979, 69, 'Cheryl Lynn', 'Cheryl Lynn', 'Got To Be Real', 2410.0),
 (2408, 1979, 68, 'England Dan and John Ford Coley', 'England Dan and John Ford Coley', 'Love Is The Answer', 2409.0),
 (2407, 1979, 67, 'Styx', 'Styx', 'Renegade', 2408.0),
 (2406, 1979, 66, 'Little River Band', 'Little River Band', 'Lonesome Loser', 2407.0),
 (2405, 1979, 65, 'McFadden and Whitehead', 'McFadden and Whitehead', "Ain't No Stoppin' Us Now", 2406.0),
 (2404, 1979, 64, 'Alicia Bridges', 'Alicia Bridges', 'I Love The Night Life', 2405.0),
 (2403, 1979, 63, 'Rickie Lee Jones', 'Rickie Lee Jones', "Chuck E's In Love", 2404.0),
 (2402, 1979, 62, 'Chic', 'Chic', 'I Want Your Love', 2403.0),
 (2401, 1979, 61, 'Dire Straits', 'Dire Straits', 'Sultans Of Swing', 2402.0),
 (2400, 1979, 60, 'Ace Frehley', 'Ace Frehley', 'New York Groove', 2401.0),
 (2399, 1979, 59, 'Bobby Caldwell', 'Bobby Caldwell', "What You Won't Do For Love", 2400.0),
 (2398, 1979, 58, 'Andy Gibb', 'Andy Gibb', "(Our Love) Don't Throw It All Away", 2399.0),
 (2397, 1979, 57, 'Earth, Wind and Fire', 'Earth, Wind and Fire', 'Boogie Wonderland', 2398.0),
 (2396, 1979, 56, 'Cher', 'Cher', 'Take Me Home', 2397.0),
 (2395, 1979, 55, 'Hot Chocolate', 'Hot Chocolate', "Every 1's A Winner", 2396.0),
 (2394, 1979, 54, 'Bad Company', 'Bad Company', "Rock 'N' Roll Fantasy", 2395.0),
 (2393, 1979, 53, 'Sister Sledge', 'Sister Sledge', 'We Are Family', 2394.0),
 (2392, 1979, 52, 'Wings', 'Wings', 'Goodnight Tonight', 2393.0),
 (2391, 1979, 51, 'John Stewart', 'John Stewart', 'Gold', 2392.0),
 (2390, 1979, 50, 'Charlie Daniels Band', 'Charlie Daniels Band', 'The Devil Went Down To Georgia', 2391.0),
 (2389, 1979, 49, 'Frank Mills', 'Frank Mills', 'Music Box Dancer', 2390.0),
 (2388, 1979, 48, 'Village People', 'Village People', 'In The Navy', 2389.0),
 (2387, 1979, 47, 'Kenny Rogers', 'Kenny Rogers', 'She Believes In Me', 2388.0),
 (2386, 1979, 46, 'Dr. Hook', 'Dr. Hook', 'Sharing The Night Together', 2387.0),
 (2385, 1979, 45, 'Sister Sledge', 'Sister Sledge', "He's The Greatest Dancer", 2386.0),
 (2384, 1979, 44, 'Toto', 'Toto', 'Hold The Line', 2385.0),
 (2383, 1979, 43, 'Bonnie Pointer', 'Bonnie Pointer', 'Heaven Must Have Sent You', 2384.0),
 (2382, 1979, 42, 'Little River Band', 'Little River Band', 'Lady', 2383.0),
 (2381, 1979, 41, 'Nicolette Larson', 'Nicolette Larson', 'Lotta Love', 2382.0),
 (2380, 1979, 40, 'Kenny Rogers', 'Kenny Rogers', 'The Gambler', 2381.0),
 (2379, 1979, 39, 'Donna Summer and Brooklyn Dreams', 'Brooklyn Dreams', 'Heaven Knows', 2380.0),
 (2378, 1979, 39, 'Donna Summer and Brooklyn Dreams', 'Donna Summer', 'Heaven Knows', 2379.0),
 (2377, 1979, 38, 'Earth, Wind and Fire', 'Earth, Wind and Fire', 'After The Love Has Gone', 2378.0),
 (2376, 1979, 37, 'Leif Garrett', 'Leif Garrett', "I Was Made For Dancin'", 2377.0),
 (2375, 1979, 36, 'Elton John', 'Elton John', "Mama Can't Buy You Love", 2376.0),
 (2374, 1979, 35, 'Barbra Streisand', 'Barbra Streisand', 'The Main Event (Fight)', 2375.0),
 (2373, 1979, 34, 'Cheap Trick', 'Cheap Trick', 'I Want You To Want Me', 2374.0),
 (2372, 1979, 33, 'Bee Gees', 'Bee Gees', 'Love You Inside Out', 2373.0),
 (2371, 1979, 32, 'Dionne Warwick', 'Dionne Warwick', "I'll Never Love This Way Again", 2372.0),
 (2370, 1979, 31, 'Peaches and Herb', 'Peaches and Herb', 'Shake Your Groove Thing', 2371.0),
 (2369, 1979, 30, 'Raydio', 'Raydio', "You Can't Change That", 2370.0),
 (2368, 1979, 29, 'Randy Vanwarmer', 'Randy Vanwarmer', 'Just When I Needed You Most', 2369.0),
 (2367, 1979, 28, 'Billy Joel', 'Billy Joel', 'My Life', 2368.0),
 (2366, 1979, 27, 'Supertramp', 'Supertramp', 'The Logical Song', 2367.0),
 (2365, 1979, 26, 'Melissa Manchester', 'Melissa Manchester', "Don't Cry Out Loud", 2366.0),
 (2364, 1979, 25, 'Jacksons', 'Jacksons', 'Shake Your Body', 2365.0),
 (2363, 1979, 24, 'Maxine Nightingale', 'Maxine Nightingale', 'Lead Me On', 2364.0),
 (2362, 1979, 23, 'Suzi Quatro and Chris Norman', 'Chris Norman', "Stumblin' In", 2363.0),
 (2361, 1979, 23, 'Suzi Quatro and Chris Norman', 'Suzi Quatro', "Stumblin' In", 2362.0),
 (2360, 1979, 22, 'Amii Stewart', 'Amii Stewart', 'Knock On Wood', 2361.0),
 (2359, 1979, 21, 'Barbra Streisand and Neil Diamond', 'Neil Diamond', "You Don't Bring Me Flowers", 2360.0),
 (2358, 1979, 21, 'Barbra Streisand and Neil Diamond', 'Barbra Streisand', "You Don't Bring Me Flowers", 2359.0),
 (2357, 1979, 20, 'Chic', 'Chic', 'Good Times', 2358.0),
 (2356, 1979, 19, 'Doobie Brothers', 'Doobie Brothers', 'What A Fool Believes', 2357.0),
 (2355, 1979, 18, 'Blondie', 'Blondie', 'Heart Of Glass', 2356.0),
 (2354, 1979, 17, 'Olivia Newton-John', 'Olivia Newton-John', 'A Little More Love', 2355.0),
 (2353, 1979, 16, 'Bee Gees', 'Bee Gees', 'Tragedy', 2354.0),
 (2352, 1979, 15, 'Pointer Sisters', 'Pointer Sisters', 'Fire', 2353.0),
 (2351, 1979, 14, 'David Naughton', 'David Naughton', "Makin' It", 2352.0),
 (2350, 1979, 13, 'Dr. Hook', 'Dr. Hook', "When You're In Love With A Beautiful Woman", 2351.0),
 (2349, 1979, 12, 'Donna Summer', 'Donna Summer', 'MacArthur Park', 2350.0),
 (2348, 1979, 11, 'Bee Gees', 'Bee Gees', 'Too Much Heaven', 2349.0),
 (2347, 1979, 10, 'Robert John', 'Robert John', 'Sad Eyes', 2348.0),
 (2346, 1979, 9, 'Anita Ward', 'Anita Ward', 'Ring My Bell', 2347.0),
 (2345, 1979, 8, 'Village People', 'Village People', 'Y.M.C.A.', 2346.0),
 (2344, 1979, 7, 'Donna Summer', 'Donna Summer', 'Hot Stuff', 2345.0),
 (2343, 1979, 6, 'Gloria Gaynor', 'Gloria Gaynor', 'I Will Survive', 2344.0),
 (2342, 1979, 5, 'Peaches and Herb', 'Peaches and Herb', 'Reunited', 2343.0),
 (2341, 1979, 4, 'Rod Stewart', 'Rod Stewart', "Da Ya Think I'm Sexy", 2342.0),
 (2340, 1979, 3, 'Chic', 'Chic', 'Le Freak', 2341.0),
 (2339, 1979, 2, 'Donna Summer', 'Donna Summer', 'Bad Girls', 2340.0),
 (2338, 1979, 1, 'Knack', 'Knack', 'My Sharona', 2339.0)]

In [18]:
%%sql

SELECT * FROM billboard_top_100_year_end
WHERE year = 1990
ORDER BY year_rank
LIMIT 5;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[(3497, 1990, 1, 'Wilson Phillips', 'Wilson Phillips', 'Hold On', 3498.0),
 (3498, 1990, 2, 'Roxette', 'Roxette', 'It Must Have Been Love', 3499.0),
 (3499, 1990, 3, "Sinead O'Connor", "Sinead O'Connor", 'Nothing Compares 2 U', 3500.0),
 (3500, 1990, 4, 'Bell Biv Devoe', 'Bell Biv Devoe', 'Poison', 3501.0),
 (3501, 1990, 5, 'Madonna', 'Madonna', 'Vogue', 3502.0)]

In [19]:
%%sql

SELECT * FROM billboard_top_100_year_end
WHERE artist = 'Queen'
AND year BETWEEN 1980 AND 1989;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
2 rows affected.

[(2446, 1980, 6, 'Queen', 'Queen', 'Crazy Little Thing Called Love', 2447.0),
 (2615, 1981, 65, 'Queen', 'Queen', 'Another One Bites The Dust', 2616.0)]

In [22]:
%%sql

SELECT * FROM billboard_top_100_year_end
WHERE artist LIKE 'Taylor%' 
AND artist != 'Taylor Swift';

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
9 rows affected.

[(3309, 1988, 20, 'Taylor Dayne', 'Taylor Dayne', "I'll Always Love You", 3310.0),
 (3343, 1988, 53, 'Taylor Dayne', 'Taylor Dayne', 'Tell It To My Heart', 3344.0),
 (3394, 1988, 100, 'Taylor Dayne', 'Taylor Dayne', 'Prove Your Love', 3395.0),
 (3432, 1989, 38, 'Taylor Dayne', 'Taylor Dayne', "Don't Rush Me", 3433.0),
 (3526, 1990, 28, 'Taylor Dayne', 'Taylor Dayne', 'Love Will Lead You Back', 3527.0),
 (3546, 1990, 48, 'Taylor Dayne', 'Taylor Dayne', 'With Every Beat Of My Heart', 3547.0),
 (3561, 1990, 63, 'Taylor Dayne', 'Taylor Dayne', "I'll Be Your Shelter", 3562.0),
 (3905, 1993, 99, 'Taylor Dayne', 'Taylor Dayne', "Can't Get Enough Of Your Love", 3906.0),
 (5492, 2006, 99, 'Taylor Hicks', 'Taylor Hicks', 'Do I Make you Proud', 5493.0)]

In [27]:
%%sql

SELECT * FROM billboard_top_100_year_end
WHERE group_name LIKE '%Rihanna%'
AND group_name != 'Rihanna'
AND artist = 'Rihanna'
AND year_rank > 50;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[(5611, 2007, 85, 'Rihanna and Sean Paul', 'Rihanna', 'Break It Off', 5612.0),
 (5718, 2008, 62, 'Rihanna feat. Ne-Yo', 'Rihanna', 'Hate That I Love You', 5719.0),
 (6157, 2011, 69, 'Rihanna feat. Calvin Harris', 'Rihanna', 'We Found Love', 6158.0),
 (6307, 2012, 79, 'Rihanna feat. Chris Brown', 'Rihanna', 'Birthday Cake', 6308.0),
 (6425, 2013, 59, 'Wale feat. Tiara Thomas or Rihanna', 'Rihanna', 'Bad', 6426.0)]

In [28]:
%%sql

SELECT *, ("High Price" - "Low Price") / 2 + "Low Price" AS "Midpoint Price" 
FROM us_pumpkin_prices 
LIMIT 5;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[(0, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 140.0, 154.75, 140.0, 154.75, 'MICHIGAN', None, 'jbo', None, None, None, None, None, None, None, None, 'N', None, 147.375),
 (1, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 145.0, 154.75, 145.0, 154.75, 'MICHIGAN', None, 'xlge', None, None, None, None, None, None, None, None, 'N', None, 149.875),
 (2, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 150.0, 154.75, 150.0, 154.75, 'MICHIGAN', None, 'med-lge', None, None, None, None, None, None, None, None, 'N', None, 152.375),
 (3, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 150.0, 150.0, 150.0, 150.0, 'MICHIGAN', None, 'sml', None, None, None, None, None, None, None, None, 'N', None, 150.0),
 (4, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 10, 1), 140.0, 154.75, 140.0, 154.75, 'MICHIGAN', None, 'jbo', None, None, None, None, None, None, None, None, 'N', None, 147.375)]

In [29]:
%%sql

SELECT * FROM us_pumpkin_prices LIMIT 5;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[(0, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 140.0, 154.75, 140.0, 154.75, 'MICHIGAN', None, 'jbo', None, None, None, None, None, None, None, None, 'N', None),
 (1, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 145.0, 154.75, 145.0, 154.75, 'MICHIGAN', None, 'xlge', None, None, None, None, None, None, None, None, 'N', None),
 (2, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 150.0, 154.75, 150.0, 154.75, 'MICHIGAN', None, 'med-lge', None, None, None, None, None, None, None, None, 'N', None),
 (3, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 150.0, 150.0, 150.0, 150.0, 'MICHIGAN', None, 'sml', None, None, None, None, None, None, None, None, 'N', None),
 (4, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 10, 1), 140.0, 154.75, 140.0, 154.75, 'MICHIGAN', None, 'jbo', None, None, None, None, None, None, None, None, 'N', None)]

In [32]:
%%sql

SELECT *, "High Price" - "Low Price" AS "Price Range"
FROM us_pumpkin_prices
ORDER BY "Price Range"
LIMIT 5;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[(11, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 10, 8), 150.0, 150.0, 150.0, 150.0, 'MICHIGAN', None, 'sml', None, None, None, None, None, None, None, None, 'N', None, 0.0),
 (16, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 10, 15), 150.0, 150.0, 150.0, 150.0, 'MICHIGAN', None, 'sml', None, None, None, None, None, None, None, None, 'N', None, 0.0),
 (3, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 9, 24), 150.0, 150.0, 150.0, 150.0, 'MICHIGAN', None, 'sml', None, None, None, None, None, None, None, None, 'N', None, 0.0),
 (7, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 10, 1), 150.0, 150.0, 150.0, 150.0, 'MICHIGAN', None, 'sml', None, None, None, None, None, None, None, None, 'N', None, 0.0),
 (21, 'PUMPKINS', 'ATLANTA', None, '24 inch bins', 'HOWDEN TYPE', None, None, datetime.date(2016, 10, 22), 150.0, 150.0, 150.0, 150.0, 'MICHIGAN', None, 'sml', None, None, None, None, None, None, None, None, 'N', None, 0.0)]

In [33]:
%%sql

SELECT COUNT(*)
FROM us_pumpkin_prices;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
1 rows affected.

[(1757,)]

In [37]:
%%sql
SELECT MAX("High Price") FROM us_pumpkin_prices;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
1 rows affected.

[(480.0,)]

In [42]:
%%sql

SELECT "Variety", COUNT(*)
FROM us_pumpkin_prices 
GROUP BY "Variety"
ORDER BY COUNT DESC;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
11 rows affected.

[('HOWDEN TYPE', 542),
 ('PIE TYPE', 468),
 ('MINIATURE', 310),
 ('FAIRYTALE', 132),
 ('CINDERELLA', 81),
 ('BIG MACK TYPE', 74),
 ('MIXED HEIRLOOM VARIETIES', 57),
 ('HOWDEN WHITE TYPE', 49),
 ('KNUCKLE HEAD', 20),
 ('BLUE TYPE', 19),
 (None, 5)]

In [44]:
%%sql

SELECT "City Name", "Variety", COUNT(*) 
FROM us_pumpkin_prices 
GROUP BY "City Name", "Variety" 
HAVING MAX("High Price") > 300 
ORDER BY "City Name";

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
5 rows affected.

[('BALTIMORE', 'CINDERELLA', 25),
 ('COLUMBIA', 'MINIATURE', 54),
 ('LOS ANGELES', 'HOWDEN TYPE', 21),
 ('SAN FRANCISCO', 'PIE TYPE', 45),
 ('SAN FRANCISCO', 'HOWDEN TYPE', 37)]

In [54]:
%%sql

SELECT "City Name", "Variety"
FROM us_pumpkin_prices
GROUP BY "City Name", "Variety"
HAVING MIN("Low Price") >= 5
ORDER BY "Variety";

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
75 rows affected.

[('NEW YORK', 'BIG MACK TYPE'),
 ('SAN FRANCISCO', 'BIG MACK TYPE'),
 ('DALLAS', 'BIG MACK TYPE'),
 ('BALTIMORE', 'BIG MACK TYPE'),
 ('BOSTON', 'BIG MACK TYPE'),
 ('BOSTON', 'BLUE TYPE'),
 ('SAN FRANCISCO', 'BLUE TYPE'),
 ('COLUMBIA', 'BLUE TYPE'),
 ('DALLAS', 'CINDERELLA'),
 ('BOSTON', 'CINDERELLA'),
 ('BALTIMORE', 'CINDERELLA'),
 ('COLUMBIA', 'CINDERELLA'),
 ('SAN FRANCISCO', 'CINDERELLA'),
 ('COLUMBIA', 'FAIRYTALE'),
 ('CHICAGO', 'FAIRYTALE'),
 ('BOSTON', 'FAIRYTALE'),
 ('BALTIMORE', 'FAIRYTALE'),
 ('DALLAS', 'FAIRYTALE'),
 ('SAN FRANCISCO', 'FAIRYTALE'),
 ('LOS ANGELES', 'HOWDEN TYPE'),
 ('BOSTON', 'HOWDEN TYPE'),
 ('COLUMBIA', 'HOWDEN TYPE'),
 ('MIAMI', 'HOWDEN TYPE'),
 ('SAN FRANCISCO', 'HOWDEN TYPE'),
 ('DALLAS', 'HOWDEN TYPE'),
 ('CHICAGO', 'HOWDEN TYPE'),
 ('ATLANTA', 'HOWDEN TYPE'),
 ('NEW YORK', 'HOWDEN TYPE'),
 ('ST. LOUIS', 'HOWDEN TYPE'),
 ('BALTIMORE', 'HOWDEN TYPE'),
 ('PHILADELPHIA', 'HOWDEN TYPE'),
 ('DETROIT', 'HOWDEN TYPE'),
 ('DALLAS', 'HOWDEN WHITE TYPE'),
 ('BALTIMORE', 'HOWDEN WHITE TYPE'),
 ('ST. LOUIS', 'HOWDEN WHITE TYPE'),
 ('DETROIT', 'HOWDEN WHITE TYPE'),
 ('CHICAGO', 'HOWDEN WHITE TYPE'),
 ('COLUMBIA', 'HOWDEN WHITE TYPE'),
 ('NEW YORK', 'KNUCKLE HEAD'),
 ('BOSTON', 'KNUCKLE HEAD'),
 ('COLUMBIA', 'KNUCKLE HEAD'),
 ('PHILADELPHIA', 'KNUCKLE HEAD'),
 ('SAN FRANCISCO', 'MINIATURE'),
 ('ST. LOUIS', 'MINIATURE'),
 ('PHILADELPHIA', 'MINIATURE'),
 ('NEW YORK', 'MINIATURE'),
 ('LOS ANGELES', 'MINIATURE'),
 ('BOSTON', 'MINIATURE'),
 ('COLUMBIA', 'MINIATURE'),
 ('ATLANTA', 'MINIATURE'),
 ('CHICAGO', 'MINIATURE'),
 ('BALTIMORE', 'MINIATURE'),
 ('CHICAGO', 'MIXED HEIRLOOM VARIETIES'),
 ('DALLAS', 'MIXED HEIRLOOM VARIETIES'),
 ('COLUMBIA', 'MIXED HEIRLOOM VARIETIES'),
 ('NEW YORK', 'MIXED HEIRLOOM VARIETIES'),
 ('BALTIMORE', 'MIXED HEIRLOOM VARIETIES'),
 ('ST. LOUIS', 'MIXED HEIRLOOM VARIETIES'),
 ('SAN FRANCISCO', 'MIXED HEIRLOOM VARIETIES'),
 ('DETROIT', 'MIXED HEIRLOOM VARIETIES'),
 ('LOS ANGELES', 'PIE TYPE'),
 ('ST. LOUIS', 'PIE TYPE'),
 ('DALLAS', 'PIE TYPE'),
 ('COLUMBIA', 'PIE TYPE'),
 ('MIAMI', 'PIE TYPE'),
 ('SAN FRANCISCO', 'PIE TYPE'),
 ('NEW YORK', 'PIE TYPE'),
 ('BOSTON', 'PIE TYPE'),
 ('BALTIMORE', 'PIE TYPE'),
 ('PHILADELPHIA', 'PIE TYPE'),
 ('CHICAGO', 'PIE TYPE'),
 ('DETROIT', 'PIE TYPE'),
 ('ATLANTA', 'PIE TYPE'),
 ('DALLAS', None),
 ('BALTIMORE', None)]

In [64]:
%%sql

SELECT artist, COUNT(*) AS "hits"
FROM billboard_top_100_year_end
GROUP BY artist
ORDER BY "hits" DESC
LIMIT 10;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
10 rows affected.

[('Elvis Presley', 36),
 ('Madonna', 36),
 ('Mariah Carey', 33),
 ('Rihanna', 33),
 ('Ludacris', 28),
 ('Elton John', 28),
 ('Beatles', 27),
 ('Michael Jackson', 26),
 ('Lil Wayne', 25),
 ('Usher', 25)]

In [69]:
%%sql

SELECT "City Name", AVG("High Price" - "Low Price") AS "Price Range"
FROM us_pumpkin_prices
GROUP BY "City Name"
ORDER BY "Price Range" DESC;

 * postgresql+psycopg2://alexandergelernter:***@localhost:5432/intro_to_sql_for_analytics
13 rows affected.

[('BOSTON', 24.394886363636363),
 ('ATLANTA', 14.232456140350877),
 ('NEW YORK', 9.357142857142858),
 ('BALTIMORE', 7.565359477124183),
 ('LOS ANGELES', 5.812096774193549),
 ('PHILADELPHIA', 5.614035087719298),
 ('SAN FRANCISCO', 5.25),
 ('DALLAS', 4.817518248175182),
 ('CHICAGO', 2.6653225806451615),
 ('DETROIT', 1.2272727272727273),
 ('ST. LOUIS', 1.1407766990291262),
 ('COLUMBIA', 0.41825095057034223),
 ('MIAMI', 0.0)]